### PR TITLE
InventoryItem & InventoryLevel support

### PR DESCRIPTION
**Pull request by clement911**
-New entities InventoryItem and InventoryLevel
-New service InventoryItemService and InventoryLevelService
-New property ProductVariant.InventoryItemId
-Move handling of Ids filter parameter in base class and removed name checking
-Incremented version

### CODE REVIEW

**Comment by clement911** [comment]
Note that running the new tests requires the `read_inventory` scope.

**Comment by clement911** [comment]
@nozzlegear Please release whenever possible :)

**Comment by nozzlegear** [comment]
Published in 4.12.0. Thank you!

**Comment by clement911** [comment]
@nozzlegear  Thanks for that 👍

**Comment by nhamid** [comment]
@clement911 Hi do you have any plans on adding methods to update inventory levels using the new endpoints? Thanks.

**Comment by clement911** [comment]
No sorry, but it should be pretty straight forward if you want to take a crack at it.

**Comment by nhamid** [comment]
:) yeah think I will I do , but think I need to update my VS to 2017 to work with .net core.. Thanks

**Pull request merged**
