### PR TITLE
Implemented the CustomerAddress resource instance

### PR DESCRIPTION
**Pull request by lasamuadib**
I have added functionality for the CustomerAddress resource of the API.  All functionality of the Admin API with the exception of bulk operations has been implemented.

### CODE REVIEW

**Comment by nozzlegear** [comment]
Awesome, thanks for the work on this! Would you mind adding some basic tests for the service? You can take a look at the ArticleService tests for inspiration: https://github.com/nozzlegear/ShopifySharp/blob/dd716d08d825eafb2b7a08538c6b014ca27e1eb3/ShopifySharp.Tests/Article_Tests.cs

**Comment by lasamuadib** [comment]
I had tests in there. Did those not get included with be pull?

**Comment by nozzlegear** [comment]
Maybe that was my mistake, I thought it said there was just the file with the new service. I see the tests now though! I'm out of town this evening but I'll run them tomorrow and get it merged asap.

**Comment by lasamuadib** [comment]
Awesome! Let me know if you run into any issues.

**Comment by nozzlegear** [comment]
Should be available in 4.7.0!

**Comment by lasamuadib** [comment]
Thank you sir!

**Comment by lasamuadib** [comment]
By chance have you looked at the changes required to implement the latest
Flurl packages?

**Comment by nozzlegear** [comment]
I was just looking at it yesterday! It's going to be a bit of a rewrite so I don't have a timeframe for it, but it's the next item on my agenda for this package.

**Comment by lasamuadib** [comment]
Joshua,

I was starting some work on expanding the CheckoutService and I ran into
something I wanted to run by you.  There are a couple of calls where I've
run into something I haven't seen with any of the other APIs.  There are
API calls such as get a single checkout or get shipping rates for a
checkout which can return a status code 202 considered successful by
CheckResponseExceptions, but also returns a response header "Retry After: "
with a numeric value of when to retry the call.  The instances of this I
found always return the root element, but it's empty.  I wanted to get your
opinion on how you think this should be handled since all of my ideas would
include changes to some of what I would consider core classes in
ShopifySharp.

Jonathan

**Comment by nozzlegear** [comment]
Hey Jonathan, to be honest I had no idea the Shopify API did that. I knew it returned 202s, but I wasn't aware the objects could be empty. What changes did you have in mind for this?

**Comment by lasamuadib** [comment]
This is what I've been testing with so far.  I wanted to keep any changes
to the core minimal and put the task of managing any retry communications
back on the client application.

To summarize:

1. I added and additional property to the element to hold the retry-after
value
2. I added some code to check if the data has values in ExecuteRequestAsync
3. Created CheckRetry which checks the status code and for a Retry-After
header and if found creates a new json object with the same original path
populating the retry_after property.

Let me know your thoughts and if you think I should try a different route.

﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
using ShopifySharp.Infrastructure;
using Newtonsoft.Json;
using System.IO;

namespace ShopifySharp
{
    public abstract class ShopifyService
    {
        private static IRequestExecutionPolicy _GlobalExecutionPolicy = new DefaultRequestExecutionPolicy();

        private static JsonSerializer _Serializer = new JsonSerializer { DateParseHandling = DateParseHandling.DateTimeOffset };

        private static HttpClient _Client { get; } = new HttpClient();

        private IRequestExecutionPolicy _ExecutionPolicy;

        protected Uri _ShopUri { get; set; }

        protected string _AccessToken { get; set; }

        /// <summary>
        /// Creates a new instance of <see cref="ShopifyService" />.
        /// </summary>
        /// <param name="myShopifyUrl">The shop's *.myshopify.com URL.</param>
        /// <param name="shopAccessToken">An API access token for the shop.</param>
        protected ShopifyService(string myShopifyUrl, string shopAccessToken)
        {
            _ShopUri = BuildShopUri(myShopifyUrl, false);
            _AccessToken = shopAccessToken;

            // If there's a global execution policy it should be set as this instance's policy.
            // User can override it with instance-specific execution policy.
            _ExecutionPolicy = _GlobalExecutionPolicy ?? new DefaultRequestExecutionPolicy();
        }

        /// <summary>
        /// Attempts to build a shop API <see cref="Uri"/> for the given shop. Will throw a <see cref="ShopifyException"/> if the URL cannot be formatted.
        /// </summary>
        /// <param name="myShopifyUrl">The shop's *.myshopify.com URL.</param>
        /// <exception cref="ShopifyException">Thrown if the given URL cannot be converted into a well-formed URI.</exception>
        /// <returns>The shop's API <see cref="Uri"/>.</returns>
        public static Uri BuildShopUri(string myShopifyUrl, bool withAdminPath)
        {
            if (Uri.IsWellFormedUriString(myShopifyUrl, UriKind.Absolute) == false)
            {
                //Shopify typically returns the shop URL without a scheme. If the user is storing that as-is, the uri will not be well formed.
                //Try to fix that by adding a scheme and checking again.
                if (Uri.IsWellFormedUriString("https://" + myShopifyUrl, UriKind.Absolute) == false)
                {
                    throw new ShopifyException($"The given {nameof(myShopifyUrl)} cannot be converted into a well-formed URI.");
                }

                myShopifyUrl = "https://" + myShopifyUrl;
            }

            var builder = new UriBuilder(myShopifyUrl)
            {
                Scheme = "https:",
                Port = 443, //SSL port
                Path = withAdminPath ? "admin" : ""
            };

            return builder.Uri;
        }

        /// <summary>
        /// Sets the execution policy for this instance only. This policy will always be used over the global execution policy.
        /// The instance will revert back to the global execution policy if you pass null to this method.
        /// </summary>
        public void SetExecutionPolicy(IRequestExecutionPolicy executionPolicy)
        {
            // If the user passes null, revert to the global execution policy.
            _ExecutionPolicy = executionPolicy ?? _GlobalExecutionPolicy ?? new DefaultRequestExecutionPolicy();
        }

        /// <summary>
        /// Sets the global execution policy for all *new* instances. Current instances are unaffected, but you can call .SetExecutionPolicy on them.
        /// </summary>
        public static void SetGlobalExecutionPolicy(IRequestExecutionPolicy globalExecutionPolicy)
        {
            _GlobalExecutionPolicy = globalExecutionPolicy;
        }

        protected RequestUri PrepareRequest(string path)
        {
            var ub = new UriBuilder(_ShopUri)
            {
                Scheme = "https:",
                Port = 443,
                Path = $"admin/{path}"
            };

            return new RequestUri(ub.Uri);
        }

        /// <summary>
        /// Prepares a request to the path and appends the shop's access token header if applicable.
        /// </summary>
        protected CloneableRequestMessage PrepareRequestMessage(RequestUri uri, HttpMethod method, HttpContent content = null)
        {
            var msg = new CloneableRequestMessage(uri.ToUri(), method, content);

            if (!string.IsNullOrEmpty(_AccessToken))
            {
                msg.Headers.Add("X-Shopify-Access-Token", _AccessToken);
            }

            return msg;
        }

        /// <summary>
        /// Executes a request and returns a JToken for querying. Throws an exception when the response is invalid.
        /// Use this method when the expected response is a single line or simple object that doesn't warrant its own class.
        /// </summary>
        /// <remarks>
        /// This method will automatically dispose the <paramref name="baseClient"/> and <paramref name="content" /> when finished.
        /// </remarks>
        protected async Task<JToken> ExecuteRequestAsync(RequestUri uri, HttpMethod method, HttpContent content = null)
        {
            using (var baseRequestMessage = PrepareRequestMessage(uri, method, content))
            {
                var policyResult = await _ExecutionPolicy.Run(baseRequestMessage, async (requestMessage) =>
                {
                    var request = _Client.SendAsync(requestMessage);

                    using (var response = await request)
                    {
                        var rawResult = await response.Content.ReadAsStringAsync();

                        //Check for and throw exception when necessary.
                        CheckResponseExceptions(response, rawResult);

                        JToken jtoken = null;

                        // Don't parse the result when the request was Delete.
                        if (baseRequestMessage.Method != HttpMethod.Delete)
                        {
                            jtoken = JToken.Parse(rawResult);
                        }

                        return new RequestResult<JToken>(response, jtoken, rawResult);
                    }
                });

                return policyResult;
            }
        }

        /// <summary>
        /// Executes a request and returns the given type. Throws an exception when the response is invalid.
        /// Use this method when the expected response is a single line or simple object that doesn't warrant its own class.
        /// </summary>
        /// <remarks>
        /// This method will automatically dispose the <paramref name="baseRequestMessage" /> when finished.
        /// </remarks>
        protected async Task<T> ExecuteRequestAsync<T>(RequestUri uri, HttpMethod method, HttpContent content = null, string rootElement = null) where T : new()
        {
            using (var baseRequestMessage = PrepareRequestMessage(uri, method, content))
            {
                var policyResult = await _ExecutionPolicy.Run<T>(baseRequestMessage, async (requestMessage) =>
                {
                    var request = _Client.SendAsync(requestMessage);

                    using (var response = await request)
                    {
                        var rawResult = await response.Content.ReadAsStringAsync();

                        //Check for and throw exception when necessary.
                        CheckResponseExceptions(response, rawResult);

                        // This method may fail when the method was Delete, which is intendend.
                        // Delete methods should not be parsing the response JSON and should instead
                        // be using the non-generic ExecuteRequestAsync.
                        var reader = new JsonTextReader(new StringReader(rawResult));
                        var data = _Serializer.Deserialize<JObject>(reader).SelectToken(rootElement);

                        if (!data.HasValues)
                        {
                            //Check for retry.
                            CheckRetry(response, ref data, rootElement);
                        }

                        var result = data.ToObject<T>();

                        return new RequestResult<T>(response, result, rawResult);
                    }
                });

                return policyResult;
            }
        }

        /// <summary>
        /// Checks a response for exceptions or invalid status codes. Throws an exception when necessary.
        /// </summary>
        /// <param name="response">The response.</param>
        public static void CheckResponseExceptions(HttpResponseMessage response, string rawResponse)
        {
            int statusCode = (int)response.StatusCode;

            // No error if response was between 200 and 300.
            if (statusCode >= 200 && statusCode < 300)
            {
                return;
            }

            var requestIdHeader = response.Headers.FirstOrDefault(h => h.Key.Equals("X-Request-Id", StringComparison.OrdinalIgnoreCase));
            string requestId = requestIdHeader.Value?.FirstOrDefault();
            var errors = ParseErrorJson(rawResponse);
            var code = response.StatusCode;
            string message = $"Response did not indicate success. Status: {(int)code} {response.ReasonPhrase}.";

            if (errors == null)
            {
                errors = new Dictionary<string, IEnumerable<string>>()
                    {
                        {
                            $"{(int)code} {response.ReasonPhrase}",
                            new string[] { message }
                        },
                    };
            }
            else
            {
                var firstError = errors.First();

                message = $"{firstError.Key}: {string.Join(", ", firstError.Value)}";
            }

            // If the error was caused by reaching the API rate limit, throw a rate limit exception.
            if ((int)code == 429 /* Too many requests */)
            {
                throw new ShopifyRateLimitException(code, errors, message, rawResponse, requestId);
            }

            throw new ShopifyException(code, errors, message, rawResponse, requestId);
        }

        /// <summary>
        /// Checks a response header for a status code 202 indicating retry.
        /// </summary>
        /// <param name="response">The response.</param>
        /// <param name="data">The json object.</param>
        /// <param name="rootElement">The root element.</param>
        public static void CheckRetry(HttpResponseMessage response, ref JToken data, string rootElement)
        {
            int statusCode = (int)response.StatusCode;

            // No error if response equals 202.
            if (statusCode != 202)
            {
                return;
            }

            // Check for Retry-After header
            var requestRetryAfter = response.Headers.FirstOrDefault(h => h.Key.Equals("Retry-After", StringComparison.OrdinalIgnoreCase));
            string requestRetry = requestRetryAfter.Value?.FirstOrDefault();

            if (!string.IsNullOrEmpty(requestRetry))
            {
                // Retry-After found generate new json object
                data = _Serializer.Deserialize<JObject>(new JsonTextReader(new StringReader($"{{\"{data.Path}\":[{{\"retry_after\":\"1\"}}]}}"))).SelectToken(rootElement);
            }
        }

        /// <summary>
        /// Parses a JSON string for Shopify API errors.
        /// </summary>
        /// <returns>Returns null if the JSON could not be parsed into an error.</returns>
        public static Dictionary<string, IEnumerable<string>> ParseErrorJson(string json)
        {
            if (string.IsNullOrEmpty(json))
            {
                return null;
            }

            var errors = new Dictionary<string, IEnumerable<string>>();

            try
            {
                var parsed = JToken.Parse(string.IsNullOrEmpty(json) ? "{}" : json);

                // Errors can be any of the following:
                // 1. { errors: "some error message"}
                // 2. { errors: { "order" : "some error message" } }
                // 3. { errors: { "order" : [ "some error message" ] } }
                // 4. { error: "invalid_request", error_description:"The authorization code was not found or was already used" }

                if (parsed.Any(p => p.Path == "error") && parsed.Any(p => p.Path == "error_description"))
                {
                    // Error is type #4
                    var description = parsed["error_description"];

                    errors.Add("invalid_request", new List<string>() { description.Value<string>() });
                }
                else if (parsed.Any(x => x.Path == "errors"))
                {
                    var parsedErrors = parsed["errors"];

                    //errors can be either a single string, or an array of other errors
                    if (parsedErrors.Type == JTokenType.String)
                    {
                        //errors is type #1

                        errors.Add("Error", new List<string>() { parsedErrors.Value<string>() });
                    }
                    else
                    {
                        //errors is type #2 or #3

                        foreach (var val in parsedErrors.Values())
                        {
                            string name = val.Path.Split('.').Last();
                            var list = new List<string>();

                            if (val.Type == JTokenType.String)
                            {
                                list.Add(val.Value<string>());
                            }
                            else if (val.Type == JTokenType.Array)
                            {
                                list = val.Values<string>().ToList();
                            }

                            errors.Add(name, list);
                        }
                    }
                }
                else
                {
                    return null;
                }
            }
            catch (Exception e)
            {
                errors.Add(e.Message, new List<string>() { json });
            }

            // KVPs are structs and can never be null. Instead, check if the first error equals the default kvp value.
            if (errors.FirstOrDefault().Equals(default(KeyValuePair<string, IEnumerable<string>>)))
            {
                return null;
            }

            return errors;
        }
    }
}

**Pull request merged**
