### PR TITLE
New properties for InventoryLevel and RefundLineItem

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by clement911** [comment]
@nozzlegear would you be able to release these?

**Comment by clement911** [comment]
@nozzlegear 🙏 
I'm sure that you are busy but hoping you get a minute to release to Nuget :)

By the way, moving forward I'd be happy to help you with the release process.
Let me know what you think.

**Comment by nozzlegear** [comment]
Sure, sorry! Right now I think the thing that slows me down the most is trying to automate the release to Nuget. Since it's a good 10-15 minutes between the time a pull request is merged and the time the tests are finished, I'm afraid I'll run out of time and forget to come back to release them. So what I really need is to figure out how I can get it to publish automatically if a test succeeds, while incrementing the minor version.

**Comment by clement911** [comment]
Good to hear from you :)

Although I don't think I fully understand.
I think you are saying that you would like the build process to auto-release to nuget if the tests are green? As opposed to you having to push a button once it's built?

**Comment by nozzlegear** [comment]
Exactly! I'm just afraid I'll merge a PR, then get distracted or have to step away while the tests are building and end up forgetting to actually push that button to publish it.

**Comment by clement911** [comment]
Oh ok hmmm maybe you can set up an email to yourself when the build completes?

**Comment by nozzlegear** [comment]
That might be possible. I think what I need to do is take a couple hours to look through the Appveyor documentation and see what it can do. Merging PRs is easy, the tedious part is just waiting for the build/test to complete plus creating the release on GitHub.

**Comment by nozzlegear** [comment]
Published on Nuget in version 4.21.3!

**Comment by clement911** [comment]
Thank you so much! 👍

**Pull request merged**
