### PR TITLE
UserService Changes for pagination

### PR DESCRIPTION
**Pull request by rohanp1903**
Please find changes for using pagination for UserService. No tests were performed by me, please double check.
This is a breaking change for the new API version, so I would appreciate if you could test and merge changes.

### CODE REVIEW

**Comment by nozzlegear** [comment]
Thanks! Unfortunately this endpoint is hard to test because it requires a Shopify Plus store to even use the Users API.

**Comment by nozzlegear** [comment]
Looks like it has some conflicts with the master branch, I'll get it fixed and merged today.

**Comment by clement911** [comment]
I don't understand @rohanp1903 . The User endpoint doesn't support paging.
The List endpoint returns the entire list of users.
https://shopify.dev/api/admin/rest/reference/plus/user?api%5Bversion%5D=2021-07#index-2021-07

So what is this about?

**Comment by clement911** [comment]
Oops please ignore my previous comment, I'm an idiot. I see now that pagination was added as of 2021-01.

**Comment by clement911** [comment]
Looks good to me, but I can't seem to view the conflicts.

**Comment by rohanp1903** [comment]
No worries @clement911 . Also, just to let you guys know, I have created a DLL in my local with my code changes and tested it and it seems to be working fine.

**Comment by clement911** [comment]
Hi @nozzlegear  , any chance you could release this one?
It's preventing us to upgrade to the latest.

**Comment by nozzlegear** [comment]
Can do! I’ll try to find some time late this evening to fix the conflicts, otherwise I’ll get this published on Thursday for sure!

--
Josh Harms

**Comment by nozzlegear** [comment]
And by Thursday I meant Friday morning 😜

**Comment by nozzlegear** [comment]
Okay, I've manually merged your changes into the master branch after fixing the conflicts and making some adjustments to add cancellation tokens to the new methods. I'll close this pull request, but [your changes have been merged here](https://github.com/nozzlegear/ShopifySharp/blob/aceef45e9d770114ede01b8115d62118c39f3864/ShopifySharp/Services/User/UserService.cs#L47). I'm going to merge a couple other things today and then publish to Nuget. Thanks for contributing!

**Comment by nozzlegear** [comment]
Published in version 5.12.0 on nuget. Thanks again for the pull request!

**Pull request closed without merging**
