### PR TITLE
Added Metafield IEnumerables to Product, ProductImage, ProductVariant, Both Collections and Orders, Customers, Pages entities

### PR DESCRIPTION
**Pull request by dkershner6**
Tested GETs as working, and also Creates using some simple code:

 Product product = new Product();
                product.Title = "Test";
                product.PublishedAt = null;
                product.Tags = "Testing";
                MetaField metafield = new MetaField();
                metafield.Namespace = "test";
                metafield.Key = "testtest";
                metafield.Value = "Really testing.";
                metafield.ValueType = "string";
                product.Metafields = new List<MetaField>() { metafield };
                product = await productService.CreateAsync(product);

Result:
image

### CODE REVIEW

**Comment by dkershner6** [comment]
Added some more: Both collections and orders, customers, pages.

Tested customers and collections.

**Comment by nozzlegear** [comment]
Nice work! Are you ready to merge this, or planning to add more first?

**Comment by dkershner6** [comment]
Let's merge it up @nozzlegear , the remaining metafields are pretty low use, and are VERY unlikely to be used on a Create (shop, for instance).

**Comment by nozzlegear** [comment]
Published in 4.15.2. Thank you very much!

**Comment by dkershner6** [comment]
All us heavy metafield users say "Thank you" back, @nozzlegear . :)

**Comment by lishanl** [comment]
🥂

**Pull request merged**
