### PR TITLE
Fix SmartCollection.UpdateProductOrder

### PR DESCRIPTION
**Pull request by foxandrewj**
SmartCollection.UpdateProductOrderAsync fixes:
- The API call returns an empty response (not the SmartCollection)
- Add additional parameter "sortOrder".

### CODE REVIEW

**Comment by nozzlegear** [comment]
Awesome! I'm on mobile right now but I'll merge ASAP




--


Josh Harms







On Fri, May 11, 2018 at 3:10 PM -0500, "Andrew Fox" <notifications@github.com> wrote:












SmartCollection.UpdateProductOrderAsync fixes:

The API call returns an empty response (not the SmartCollection)
Add additional parameter "sortOrder".




You can view, comment on, or merge this pull request online at:


  https://github.com/nozzlegear/ShopifySharp/pull/246

Commit Summary

  Fix SmartCollction.UpdateProductOrder
  Fix SmartCollction.UpdateProductOrder
  Merge branch 'master' of https://github.com/foxandrewj/ShopifySharp
  Merge branch 'master' of https://github.com/foxandrewj/ShopifySharp
  Merge branch 'master' of https://github.com/foxandrewj/ShopifySharp


File Changes

  
    M
    ShopifySharp.Tests/SmartCollection_Tests.cs
    (60)
  
  
    M
    ShopifySharp/Services/SmartCollection/SmartCollectionService.cs
    (8)
  


Patch Links:

  https://github.com/nozzlegear/ShopifySharp/pull/246.patch
  https://github.com/nozzlegear/ShopifySharp/pull/246.diff

**Comment by nozzlegear** [comment]
Okay, so just to be clear the `UpdateProductOrder` API call doesn't return anything and it was a mistake saying it did return a `SmartCollection`?

**Comment by foxandrewj** [comment]
Correct.  It does not return a smart collection.  It returns empty, just like a delete.
[https://help.shopify.com/api/reference/products/smartcollection#order]( https://help.shopify.com/api/reference/products/smartcollection#order)

**Comment by nozzlegear** [comment]
Cool. Technically a breaking change but anybody using the current implementation is getting exceptions anyway, so I'll merge this now.

**Pull request merged**
