### PR TITLE
Changed InventoryLevel.Available from int to long

### PR DESCRIPTION
**Pull request by clement911**
I came across in production an inventory_level with a available quantity lower than int.MinValue

image

### CODE REVIEW

**Comment by nozzlegear** [comment]
Thanks for the PR! I'm not sure I'm comfortable with altering the exception message right now. It's probably a bad practice, but it's likely that some people are checking the message value when catching exceptions, as I used to recommend they do that for rate exceptions. I think it should still be possible to access that request ID if you try to cast a generic exception to a ShopifyException?

**Comment by clement911** [comment]
Fair enough.
I've reverted that part.

**Comment by nozzlegear** [comment]
Thanks! Published in 5.2.0

**Comment by clement911** [comment]
Thank you

**Pull request merged**
