### PR TITLE
Added the Dictionary and Raw Query String Abilities to IsAuthenticProxyRequest

### PR DESCRIPTION
**Pull request by dkershner6**
Mostly so I can stop writing AuthorizationService.IsAuthenticProxyRequest(AuthorizationService.ParseRawQuerystring(queryString).Select(kvp => new KeyValuePair<string, StringValues>(kvp.Key, kvp.Value)), skey);

### CODE REVIEW

**Comment by nozzlegear** [comment]
That's a great improvement! Would you mind adding a test for each of these to the `Authorization_Tests.cs` file? They should pass if you use the values from the `Validates_Proxy_Requests` test.

**Comment by dkershner6** [comment]
They have been added @nozzlegear .  I ran them, then realized I didn't have the environment variables set up, but they should work.

**Comment by nozzlegear** [comment]
Awesome! I've merged your PR, but I'm not at my office right now so I won't be able to publish a new release for a few hours.

**Comment by nozzlegear** [comment]
Alright, published in 4.16.1. Thank you very much!

**Pull request merged**
