### PR TITLE
Retry only on 429 caused by leaky bucket

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by nozzlegear** [comment]
It looks like this breaks the fulfillment tests, since they're one of the things with the dev shop rate limit. Any suggestion on fixing them? I'm thinking just using the "dumb" retry policy maybe.

**Comment by clement911** [comment]
The dumb retry policy was also enhanced to not retry on non leaky bucket breaches.
How about applying a retry or wait in the tests directly?

**Comment by clement911** [comment]
Or maybe we could add a constructor bool parameter to the the policies, to specific whether it should retry on non bucket breach?

**Comment by nozzlegear** [comment]
I like the constructor approach, that way we can default to this new behavior but make it possible to use the old behavior in case somebody was relying on it. Would you be able to create a pull request for that?

**Comment by clement911** [comment]
Will do shortly.

**Comment by clement911** [comment]
see https://github.com/nozzlegear/ShopifySharp/pull/467

**Comment by nozzlegear** [comment]
Published in 5.0.1, thank you!

**Pull request merged**
