### PR TITLE
Users API

### PR DESCRIPTION
**Pull request by clement911**
This PR implements the user API. https://help.shopify.com/api/reference/user
It is one of the simplest API.
I wrote a couple of tests but unfortunately I'm not able to run them because I don't have access to a Shopify Plus account.

@vleontyev  any chance you could run the tests?

### CODE REVIEW

**Comment by ernestogutierrez** [comment]
@clement911 if you are a Shopify Partner I think you can use a development store to use your tests with the Shopify Plus API. 

Have you tried that?

**Comment by clement911** [comment]
l did try that but it doesn't work, even if creating a private app on the dev store. Shopify returns 404. I was told it needs to be enabled by Shopify, even on test stores! I asked them but I haven't heard back yet...

**Comment by nozzlegear** [comment]
I've had the same experience. The tests for this package on AppVeyor are using a private app, but still don't have access to the Plus APIs 🤷

**Comment by nozzlegear** [comment]
Okay, this should be available on Nuget with version 4.4.0. Thanks for the PR @clement911!

**Comment by clement911** [comment]
Thanks!

**Comment by clement911** [comment]
FYI someone at Shopify enabled the Gift Card and User APIs on my partner store and it is working nicely!

**Pull request merged**
