### PR TITLE
PrepareQuerystring, use StringComparer.Ordinal for query ordering

### PR DESCRIPTION
**Pull request by yuvalsade**
support uppercase querysting parameters for request authentication.
shopify is using ruby ordering (A > a > z), c# default is  ( z > A > a), it needs to be done the same, so that requests with upper case parameters would not fail authentication.

### CODE REVIEW

**Comment by yuvalsade** [comment]
AuthorizationService/EncodeQuery
s.Replace("%", "%25").Replace("&", "%26"), misses on some cases, changed it to Uri.UnescapeDataString

**Comment by nozzlegear** [comment]
Good catch! I don't have the foggiest idea about how Ruby does anything, so I would not have known about this.

**Comment by yuvalsade** [comment]
can you add me to the wall? :)

**Comment by nozzlegear** [comment]
Sure!

**Comment by nozzlegear** [comment]
Your changes are published on Nuget in 4.15.1. Thank you!

**Pull request merged**
