### PR TITLE
Fix for date deserialization when JSON contains dates lower than DateTime.MinValue

### PR DESCRIPTION
**Pull request by clement911**
Fixes https://github.com/nozzlegear/ShopifySharp/issues/803

### CODE REVIEW

**Comment by clement911** [comment]
@nozzlegear @davidkdb here is my PR to fix https://github.com/nozzlegear/ShopifySharp/issues/803
I've made a simple fix for now but this should open up more flexibility in the future for the host application to be able to subscribe to an event when invalid dates are detected and apply custom logic.

**Comment by clement911** [comment]
@nozzlegear I'm bumping this up for your attention as this seems to be occurring again today, i.e. Shopify is sending webhooks with invalid dates.
Without this fix, I have to manually edited webhook JSONs to fix the invalid dates. 
Are you able to push a release for this fix?

**Review by nozzlegear — APPROVED** [review]

**Comment by nozzlegear** [comment]
Thanks for the fix @clement911! Once the unit tests finish running I'll be able to publish to nuget, but I need to step out of the house in a few minutes. I'll set a reminder to publish this once I'm back, but feel free to ping me again if it seems like I forgot!

**Comment by clement911** [comment]
That's much appreciated @nozzlegear 
I think the tests are all green: https://github.com/nozzlegear/ShopifySharp/actions/runs/3389537167

**Comment by nozzlegear** [comment]
Published in 5.18.7 on nuget! Thanks a ton for investigating and debugging. 🕵️

**Comment by clement911** [comment]
Awesome. Thanks for the quick release!

**Comment by davidkdb** [comment]
It's not published yet here?

**Comment by nozzlegear** [comment]
@davidkdb There's a little bit of a delay between when the package gets published to nuget and when nuget indexes the new version and makes it available for search/download. Sometimes it can take up to an hour.

**Comment by davidkdb** [comment]
Still not available for download....

**Comment by clement911** [comment]
https://www.nuget.org/packages/ShopifySharp/5.18.7
Isn't this what   you need?

**Comment by davidkdb** [comment]
Thank you :-)

It was just not visible on: https://github.com/nozzlegear/ShopifySharp

**Comment by davidkdb** [comment]
BTW: After the fix, accepts_marketing_updated_at seems to not work anymore with invalid null date. So what was working, is not working anymore.

**Comment by clement911** [comment]
Can you explain in more detail what is not working? Or even better if you can create a test that shows the issue?

**Comment by davidkdb** [comment]
This data is received from the orders updated or order created webhook. So this is the order data.

We just do:

```
ShopifySharp.Order orderData = null;
                            try
                            {
                                orderData = JsonConvert.DeserializeObject<ShopifySharp.Order>(bodyText);
                            }
```

I have removed most info, and made some adjustments in id's for security and privacy reasons. As you can see the accepts_marketing_updated_at has an invalid date, and the code fails at the DeserializeObject pointing to accepts_marketing_updated_at

```
{
    "id": 1010101,
    "customer":
    {
        "id": 01010101,
        "accepts_marketing_updated_at": "0000-12-31T18:09:24-05:50",
        "marketing_opt_in_level": "unknown",
        "tax_exemptions": [],
        "email_marketing_consent":
        {
            "state": "subscribed",
            "opt_in_level": "unknown",
            "consent_updated_at": null
        },
        "sms_marketing_consent":
        {
            "state": "subscribed",
            "opt_in_level": "single_opt_in",
            "consent_updated_at": "2021-07-09T19:31:42-05:00",
            "consent_collected_from": "OTHER"
        },
        "admin_graphql_api_id": "gid://shopify/Customer/01010101"
    },
    "discount_applications": [],
    "fulfillments": []
}
```

**Comment by clement911** [comment]
Please try to deserialize as follows:

```csharp
var order = ShopifySharp.Infrastructure.Serializer.Deserialize<Order>(json);
```

**Comment by clement911** [comment]
@davidkdb  did that fix your issue?

I also just pushed a new [PR](https://github.com/nozzlegear/ShopifySharp/pull/805) to handle invalid dates returned by the API (as opposed to invalid dates in webhooks)

**Pull request merged**
