### PR TITLE
New property line.TipPaymentGatewaySpecified to determine whether a l…

### PR DESCRIPTION
**Pull request by clement911**
…ine is a tip line.

### CODE REVIEW

**Comment by clement911** [comment]
Thank @nozzlegear. Could you publish a new package?

**Comment by clement911** [comment]
@nozzlegear ?

**Comment by clement911** [comment]
Awesome. Thanks!

**Comment by nozzlegear** [comment]
Hey @clement911, I can't seem to find this property in the docs. Should it be nullable, and does it need a `JsonProperty` attribute?

**Comment by nozzlegear** [comment]
I've made it nullable and added the `JsonProperty` attribute for now. Let me know if that's wrong!

**Comment by clement911** [comment]
@nozzlegear no this is not an API property and shouldn't be annotated with JsonProperty.
It's a built-in feature of json.net. The bool property will be set to true if present in the payload, otherwise false. It is useful to differentiate between a null value (true) and the absence of value (false), since the underlying property will be null in the .net object in both cases.

See https://stackoverflow.com/a/61532883

https://dotnetfiddle.net/Iyry36

https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_DefaultContractResolver_IgnoreIsSpecifiedMembers.htm

**Comment by nozzlegear** [comment]
Oh neat! I don't think I've seen that before. I'll revert my changes.

**Comment by nozzlegear** [comment]
Reverted in 5.14.4!

**Comment by clement911** [comment]
Thanks 😀

**Comment by clement911** [comment]
I noticed you added a JsonIgnore attribute. I'm not sure if this will have an impact.

**Comment by clement911** [comment]
I tested and it works fine so we're all good 👍

**Pull request merged**
