### PR TITLE
Added HarmonizedSystemCode and CountryCodeOfOrigin in Inventory Item

### PR DESCRIPTION
**Pull request by ajayak**
Added missing properties to `InventoryItem`

https://help.shopify.com/en/api/reference/inventory/inventoryitem

### CODE REVIEW

**Comment by clement911** [comment]
Thank you I had a quick look at your PR but I think I spotted a few issues.

`HarmonizedSystemCodes` doesn't exist in inventoryitem. Typo?
`country_code_of_origin` should be `harmonized_system_code`. Typo?

Make sure you run a test to verify the properties get populated correctly. That should catch any typo.

Also while you are at it could you also add the remaining missing properties, such as `province_code_of_origin` and `requires_shipping` ?

**Comment by ajayak** [comment]
> Thank you I had a quick look at your PR but I think I spotted a few issues.
> 
> `HarmonizedSystemCodes` doesn't exist in inventoryitem. Typo?
> `country_code_of_origin` should be `harmonized_system_code`. Typo?
> 
> Make sure you run a test to verify the properties get populated correctly. That should catch any typo.
> 
> Also while you are at it could you also add the remaining missing properties, such as `province_code_of_origin` and `requires_shipping` ?

Here you go @clement911 :)
> country_code_of_origin should be harmonized_system_code. Typo?
These are 2 separate properties.

**Comment by clement911** [comment]
Thanks. Looks good to me!

**Comment by ajayak** [comment]
@nozzlegear is it possible to create a minor release with this PR? We need this soon :)

**Comment by nozzlegear** [comment]
Sure! I'll merge and let the tests run overnight, then publish once I'm up.

**Comment by nozzlegear** [comment]
Published in version 4.21.0 on nuget. Thanks for the pull request!

**Pull request merged**
