### PR TITLE
V5 contrib 4

### PR DESCRIPTION
**Pull request by clement911**
Fixed all tests compile errors + migrated more services to use the Service base class methods.

### CODE REVIEW

**Comment by clement911** [comment]
https://github.com/nozzlegear/ShopifySharp/issues/462

**Comment by clement911** [comment]
Alright, I was able to test cursor pagination and it appears to work nicely.
All the tests now compile and I think you can merge and release a new pre-release version.
Are you able to run all the tests and report which one fail?

ps:
I added new base service methods to DRY out POST/PUT/DELETE.
So far only migrated Webhook and RecurringCharge services.
It should be trivial to migrate other services.

**Comment by clement911** [comment]
At this point I implemented almost everything I had in mind mind.

Regarding 'Fields', I still think we should add it to `ListFilter<T>`. This way it can be auto loaded automatically like 'Limit' does. What do you think?

Also, what about renaming `ListFilter<T>` to `PageFilter<T>`?

**Comment by clement911** [comment]
I converted many service methods to use the base service methods (including POST/DELETE/PUT), but not all of them.
If you have some energy left, feel free to have a go :) Otherwise, this might not be critical and can be migrated over time...

**Comment by clement911** [comment]
Ready for merge.

**Comment by nozzlegear** [comment]
> At this point I implemented almost everything I had in mind mind.
> 
> Regarding 'Fields', I still think we should add it to `ListFilter<T>`. This way it can be auto loaded automatically like 'Limit' does. What do you think?
> 
> Also, what about renaming `ListFilter<T>` to `PageFilter<T>`?

Yes I think we should add the `Fields` property to the filter so it can be autoloaded. I'm working on the package right now and will try to fit this in. As for renaming the class, I've thought about it and I like `ListFilter` more than `PageFilter`, simply because we're using it in `ListAsync` methods so it fits the name a little better.

**Pull request merged**
