### PR TITLE
Added missing Shop.UpdatedAt property

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by nozzlegear** [comment]
Thanks for the pull request! I'll get this published soon, please ping me if it seems like I've forgotten. I'm trying to rework the automatic publish so that CI builds will automatically publish prerelease versions and wait for me to press a button to release the full version. I can't seem to get it to work correctly with AppVeyor so I'm thinking about moving to GitHub Actions.

**Comment by clement911** [comment]
That seems like a pretty good idea!
Will these pre releases automatically build from master on each commit?

**Comment by nozzlegear** [comment]
Exactly! I can get the prereleases publishing easily, it's the "don't release until I say so" part that's giving me trouble.

**Comment by nozzlegear** [comment]
Published in 5.1.1!

**Pull request merged**
