### PR TITLE
Upgraded to 2020-10 + added additional properties.

### PR DESCRIPTION
**Pull request by clement911**
@nozzlegear nothing major here, should be ready for merge.

Personally it's mostly to add the new `status` field on products, which is a great new feature.
But I also added a couple of newly added properties with 2020-10.

### CODE REVIEW

**Comment by clement911** [comment]
Hi @nozzlegear , any chance you could take a look in the next few days?

**Comment by nozzlegear** [comment]
Yep, I'm planning to do some maintenance on this package very soon! I was sick for a while but I'm feeling better now,  just need to get caught up on my client projects first and then I can review/merge everything. 

--
Josh Harms

**Comment by clement911** [comment]
Sure thing, thanks for the update!

**Comment by nozzlegear** [comment]
Yeah, I had to regenerate the nuget API key. I did that last night and updated the repo but it seems it still did not publish. Looking into it!

--
Josh Harms

**Comment by clement911** [comment]
Got it, thanks for update .

**Comment by nozzlegear** [comment]
Okay, sorry for the big delay here. I've got it figured out, I'll be publishing a new version on Monday!

**Comment by nozzlegear** [comment]
Published on nuget in version 5.8.0! Sorry again for the delay, thanks for being patient :heart:

**Comment by clement911** [comment]
Awesome, thanks!

**Pull request merged**
