### PR TITLE
Add missing fields to Shop, Customer and Order, and fix tests for shop in Norway

### PR DESCRIPTION
**Pull request by Zikoat**
This PR closes:
* https://github.com/nozzlegear/ShopifySharp/issues/653
* https://github.com/nozzlegear/ShopifySharp/issues/671
* https://github.com/nozzlegear/ShopifySharp/issues/574
* https://github.com/nozzlegear/ShopifySharp/issues/521

### CODE REVIEW

**Comment by nozzlegear** [comment]
Sure! I'll try to get this reviewed, merged and published some time today or tomorrow at the latest.

--
Josh Harms

**Comment by Zikoat** [comment]
@nozzlegear Could you review this again? I also changed CheckoutToken to String.

**Comment by Zikoat** [comment]
@nozzlegear Could you take a look at this and see if you could get it published?

**Comment by nozzlegear** [comment]
Sure thing, sorry! I've been super busy and let this get away from me. I'll review it within the next few days.

--
Josh Harms

**Review by nozzlegear — APPROVED** [review]

**Comment by nozzlegear** [comment]
Published in v5.14.0 on nuget. Thank you very much for the pull request!

**Pull request merged**
