### PR TITLE
Fixed typo in type name for Order.po_number

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by clement911** [comment]
@nozzlegear FYI I did another release but it looks like the nuget key will expire in 2 days.
Are you able to generate a new one?

image

**Comment by nozzlegear** [comment]
Oh nice, good catch! I'll regenerate it.

**Comment by nozzlegear** [comment]
@clement911 I've regenerated the Nuget key. Did you need me to approve a new release, or was it already released?

**Comment by clement911** [comment]
Thank you 👍
No action required on your part for now.

**Pull request merged**
