### PR TITLE
Minor bugs in Shopify Payments filter classes

### PR DESCRIPTION
**Pull request by clement911**
Technically there is a small breaking change but without the change the filter is unusable so I would recommend merging anyway.

### CODE REVIEW

**Comment by clement911** [comment]
Hi @nozzlegear 

Here is another PR to release when you get a chance :)

**Comment by nozzlegear** [comment]
I've got some free time on Monday, I'll get this merged in and published!

**Comment by clement911** [comment]
Sweet!

**Comment by clement911** [comment]
Thanks for the merge @nozzlegear. Is there anything preventing a release or you just haven't had the time yet?

**Comment by nozzlegear** [comment]
Yes, sorry! The tests are failing for I think product variants. Something with the changes to the inventory and location API, the tests most be using the old deprecated props. I just haven't had the time to fix the yet! I will get this released as soon as I can.

--
Josh Harms

**Comment by clement911** [comment]
got it, thanks for the update

**Comment by nozzlegear** [comment]
I should have time to get this fixed and published on Monday again!

**Comment by clement911** [comment]
That would be great!

**Pull request merged**
