### PR TITLE
4.0 - .NET Standard support.

### PR DESCRIPTION
**Pull request by nozzlegear**
Now that the 4.0 branch is building and running automated tests (#118) on AppVeyor, I'm opening this pull request to track further progress and let people who *really* need dotnet core support *right now* use the latest version. AppVeyor is automatically building the 4.0 branch and **saving the artifacts [right here](https://ci.appveyor.com/project/nozzlegear/shopifysharp/build/4.0.9/artifacts)**. You can use the zip file or the nuget package to add ShopifySharp 4.0 to your project.

Note that major changes are still planned for this branch, and I make no guarantee that the AppVeyor builds will be compatible with one another. In fact, I guarantee that they won't be because I still have breaking changes to commit. Use at your own risk!

For those planning on building features for the 4.0 release, ShopifySharp is now using [xUnit](https://xunit.github.io/) for tests. New tests should all follow the format of other tests in 4.0. You can use the [Article](https://github.com/nozzlegear/ShopifySharp/blob/4.0/ShopifySharp.Tests/Article_Tests.cs) test as an example, **but I would highly recommend that you [use the provided ShopifySharp Test snippet in the VSCode folder instead](https://github.com/nozzlegear/ShopifySharp/blob/4.0/.vscode/snippets.csharp.json)**. Create a new `*_Tests.cs` file and type `test-shopifysharp` in VSCode:

shopifysharp-test

Some to-do items that I'm tracking with this pull request, in addition to all of the open [issues marked for milestone 4.0](https://github.com/nozzlegear/ShopifySharp/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0):

- [x] 4.0 targets .NET Standard 1.6, which [should be compatible](https://github.com/dotnet/standard/blob/master/docs/versions.md) with .NET Framework 4.6.1. Does that mean it can be installed in a 461 project without explicitly targeting 461?
- [x] Merge changes that have been committed to the master branch but not to 4.0 (Refund service, etc.)
- [x] Rename `ShopifyEvent` to `Event`.

### CODE REVIEW

**Comment by clement911** [comment]
Woo great stuff.  Thanks for all your efforts on this!

**Comment by nozzlegear** [comment]
My pleasure! I'm really looking forward to getting a Shopify app running on dotnet core, so this can't come soon enough.

**Comment by vinhch** [comment]
Event entity still have the `Shopify` prefix :D

**Comment by nozzlegear** [comment]
Thanks for the heads-up @vinhch! I had intended to leave `ShopifyEvent` prefixed because I thought it would clash with a .NET `Event` class, but I seem to have had that confused with the `event` keyword instead. I'll make sure it gets unprefixed!

**Comment by nozzlegear** [comment]
Will be returning to this PR this weekend to hopefully get it finished up and merged, just been sidetracked with a major project.

**Comment by nozzlegear** [comment]
Looks like all tests are passing, and all of the major changes are now committed! I just need to update the documentation and add some tests for partial object updates. Once that's done this PR can be merged and v4 will be released. 🎉

**Comment by clement911** [comment]
Congrats!!!

**Comment by Kirlac** [comment]
Just wanted to give you a heads up, I was having issues with the [`IsAuthenticWebhook(IEnumerable<KeyValuePair<string, StringValues>> requestHeaders, string requestBody, string shopifySecretKey)`](https://github.com/nozzlegear/ShopifySharp/blob/4.0/ShopifySharp/Services/Authorization/AuthorizationService.cs#L152) function. It was looking for the header `X-Shopify-Hmac-SHA256` but on the requests I was receiving it was coming through as `X-Shopify-Hmac-Sha256`

I worked around it temporarily by removing and readding the header with uppercase "SHA" first, but you may want to make the check case insensitive. I considered fixing it myself and issuing a PR, but it seemed like a lot of work for a one line change :D

Great work by the way. You've made my job of integrating with shopify significantly easier!

**Comment by nozzlegear** [comment]
@Kirlac Thanks for the warning! Case-insensitive checking is a great suggestion, I believe it's what I already do in the JS version of this lib too. I'll make sure it gets in!

**Comment by nozzlegear** [comment]
Merged! That took far longer than I thought it would. All tests are passing and I'm planning on publishing to Nuget by Friday evening.

**Comment by nozzlegear** [comment]
v4 has been released on Nuget! It supports .NET Standard 1.4+ and .NET Framework 4.5+. My next task will be updating all of the current guides and the book for those that have it.

**Comment by clement911** [comment]
🥇 Congratulations!!! Thank you very much.

Are there any known issues when migrating from v3?
Is it just a matter of fixing compile errors?

**Comment by nozzlegear** [comment]
Thanks! There are no known issues as far as I'm aware, I was able to migrate one of my own apps pretty easily. The biggest changes will be removing the `Shopify` prefix from everything, passing an id to any update methods you already use, and changing `RequestEngine.ExecutionPolicy = ...` to `ShopifyService.SetGlobalExecutionPolicy(policy)` or `service.SetExecutionPolicy(policy)`. if you use execution policies.

**Comment by clement911** [comment]
That sounds easy enough! I think I'll wait until asp.net core 2.0 is released and migrate to ShopifySharp v4 at the same time,

**Pull request merged**
