### PR TITLE
 Changing Fulfillment.LocationId from string to long?

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by nozzlegear** [comment]
Published in 4.19.0!

**Comment by clement911** [comment]
Thank you so much @nozzlegear 👍

**Comment by clement911** [comment]
By the way, congrats on 100 releases!

**Comment by nozzlegear** [comment]
🎉 Woohoo! It couldn't have been done without contributions from people like you -- and without help from you in particular -- so thank _you_ very much for all the help you've given over the past couple of years!

**Pull request merged**
