### PR TITLE
Add Product model

### PR DESCRIPTION
**Pull request by Yitzchok**

### CODE REVIEW

**Comment by nozzlegear** [comment]
Thanks Yitzchok! 

This looks great, I've been meaning to add the Product service for a long time now. It'll need some test coverage before I can safely merge it into master, though. If you don't have the time to set up tests, just let me know. I'd be happy to do it myself sometime this week. 

One quick question, what's the reasoning behind setting `RequestEngine` to public? I don't have a problem with it, just want to know the use case.

**Comment by Yitzchok** [comment]
I will try to add tests tomorrow.

The reason I made RequestEngine public is so that someone can now add support for other calls for shoplify (for example Products) in his own project that isn't yet supported in the core framework.

**Comment by Yitzchok** [comment]
I added tests

**Comment by nozzlegear** [comment]
Awesome, this looks good. All of the tests are passing, so I'm going to merge it and then update the Nuget package.

Thanks Yitzchok!

**Pull request merged**
