### PR TITLE
Added Gift Card Adjustment Service

### PR DESCRIPTION
**Pull request by SeanoNET**
A new Gift Card Adjustment service as discussed on #414

### CODE REVIEW

**Comment by nozzlegear** [comment]
Woops I'm sorry, I didn't see this pull request! I'll review and merge it soon.

**Comment by nozzlegear** [comment]
Sorry for the delay. This has been published in 4.22.0 on nuget. Thanks for contributing!

**Comment by SeanoNET** [comment]
Hi @nozzlegear - The latest version on nuget doesn't seem to have the gift card adjustment service in it? Also the latest release on Github releases is [4.22.0](https://github.com/nozzlegear/ShopifySharp/releases/tag/4.22.0) however the latest nuget package is [4.21.8](https://www.nuget.org/packages/ShopifySharp/4.21.8)

**Comment by nozzlegear** [comment]
Hmm something must have gone wrong with my automated publish setup. I’ll get it fixed today.

**Comment by nozzlegear** [comment]
Okay, _now_ it should be published in 4.22.1.

**Comment by SeanoNET** [comment]
Perfect, thanks!

**Pull request merged**
