### PR TITLE
PriceRule not respecting BOGO type rules + new gate scopes

### PR DESCRIPTION
**Pull request by zxed**
PriceRule was missing some additional id lists and attributes; resulting in BOGO type discount price rules being incorrectly created as 100% off discounts

### CODE REVIEW

**Comment by zxed** [comment]
@nozzlegear planning to merge this into the code base?

**Comment by CrimsonOrion** [comment]
Any word on this? I could really use it as well.

**Comment by zxed** [comment]
P.s I have a fork, with updated branch merge. Should be public. You can
build that. That’s what I did for our app which needed to be on the more
recent api level.

**Comment by nozzlegear** [comment]
Oh sorry, I meant to merge this with my last batch of merges. Will publish soon!

**Pull request merged**
