### PR TITLE
New scopes for multi-location

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by clement911** [comment]
see https://help.shopify.com/api/tutorials/inventory-migration-guide

**Comment by nozzlegear** [comment]
Great! Would you mind adding some of the other missing ones discussed in the recent issue you opened? (I'd link but I'm on mobile)

**Comment by clement911** [comment]
Ok I will get to it as soon as I can!

**Comment by clement911** [comment]
All done.
Yeah for vNext I think we should remove the enum but a constants class could be useful with all known values.

**Comment by nozzlegear** [comment]
Great! I agree, it'd be nice to get the same functionality back in but with constants.

**Comment by nozzlegear** [comment]
Published in 4.10.2

**Pull request merged**
