### PR TITLE
Create ShopifySmartCollectionRules.cs

### PR DESCRIPTION
**Pull request by ishahrier**
TODO : all properties in this class should map to enums
For the time being string is enough

### CODE REVIEW

**Comment by nozzlegear** [comment]
Thanks for all the work @ishahrier. I've been out sick the last few days and haven't had a chance to get stuff merged yet. I'll try to get started tonight or possibly tomorrow.

**Comment by ishahrier** [comment]
that would be awesome!

**Comment by nozzlegear** [comment]
I've got your four PRs merged into the master branch, and they should now be available on Nuget with ShopifySharp v1.15.0. Thanks for the contributions!

Do you have any plans to build out a `ShopifySmarCollectionService` to interact with the API? If not, I'll add it to my own todo list.

**Comment by nozzlegear** [comment]
Just as a sidenote: in the future it'd be best to fork the project, make all of your changes at once, and then submit one big pull request instead of one pull request per file. It'll make things easier for everyone to track and test.

**Pull request merged**
