### PR TITLE
Allow processed_at_min / processed_at_max for orders/count.json

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by clement911** [comment]
Hi @nozzlegear , any change you can merge that in?

**Comment by nozzlegear** [comment]
Woops, I'll merge as quickly as possible! I'm out of town until Sunday morning, once I'm back I'll get it merged and published. Sorry for the delay!

--
Josh Harms

**Comment by rperez-rosario** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by clement911** [comment]
No worries, thanks @nozzlegear

**Comment by clement911** [comment]
hi @nozzlegear , any chance you can do a release?

**Comment by nozzlegear** [comment]
Woops, yes I can! I'll get a new release out today. 

--
Josh Harms

**Comment by clement911** [comment]
Awesome thank you

**Comment by nozzlegear** [comment]
Published in version 5.12.1 on nuget!

**Pull request merged**
