### PR TITLE
Shopify payments service + multi currency properties

### PR DESCRIPTION
**Pull request by clement911**
Added Shopify Payments service + tests to fetch payouts, balance, transactions and disputes.
Added few properties related to multi-currency support.
Incremented version.

Docs:
https://help.shopify.com/en/api/guides/multi-currency-migration-guide
https://help.shopify.com/en/api/reference/shopify_payments

### CODE REVIEW

**Comment by clement911** [comment]
Hi @nozzlegear , any chance you could push this to nuget?

**Comment by nozzlegear** [comment]
Yes, sorry! I missed this. I've got the day off tomorrow and was planning to do a little open source work, so I'll make sure this gets published.

--
Josh Harms

**Comment by clement911** [comment]
That's great thank you!

**Comment by nozzlegear** [comment]
No problem, thank you for the PR!

**Pull request merged**
