### PR TITLE
New Authorize overload to retrieve granted scopes.

### PR DESCRIPTION
**Pull request by clement911**
`GrantedScopes` is a `string[]` because it may contain values not present in the `AuthorizationScope` enum.

### CODE REVIEW

**Comment by clement911** [comment]
I also just added a couple of missing properties to `Shop`.

**Comment by nozzlegear** [comment]
Cool! Could you possibly rename the `Authorize2` function to something like `AuthorizeWithAuthorizationResult` or something like that? Just looking for a little bit more descriptive name. In 5.0 we should replace both functions with your new one.

**Comment by clement911** [comment]
Done.

**Comment by clement911** [comment]
Btw, do you have a roadmap or specific goals for 5.0?

**Comment by nozzlegear** [comment]
Woops didn't mean to close that.

**Comment by nozzlegear** [comment]
I don't have anything specific in mind for 5.0, nor do I have a timeline planned. Right now I'm just waiting for enough breaking changes to pile up before starting on it, but luckily we don't have many of those waiting right now.

**Comment by nozzlegear** [comment]
Published in 4.11.0

**Comment by clement911** [comment]
Thanks!

**Pull request merged**
