### PR TITLE
Preserving timezone info when deserializing dates

### PR DESCRIPTION
**Pull request by clement911**
A customer pointed out a time zone issue.
After investigating, the issue turned out to come from ShopifySharp.

In v4 all date entities were changed from DateTime to DateTimeOffset.
However, the value is still being automatically converted to the machine's time zone automatically!

I blame Json.NET for this weird default behaviour.

This pulls request forces Json.NET to correctly parse the timezone information.

### CODE REVIEW

**Comment by clement911** [comment]
Hi @nozzlegear,
sorry for the prodding but any chance we can get this released?

**Comment by nozzlegear** [comment]
Yes, sorry! Haven't forgotten about this and the other open pull request, I've just been traveling. I'll release them within a few hours!

**Comment by nozzlegear** [comment]
Released in 4.6.0!

**Comment by clement911** [comment]
You're a legend.
Happy traveling!

**Pull request merged**
