### PR TITLE
Abandoned Checkout

### PR DESCRIPTION
**Pull request by mobbsie**
Hi @nozzlegear,

This is the code I have modified from the core created by @alectec for the Abandoned Checkout functionality.  I have tested this with our own store and it is working correctly.  I haven't written a test case for it though in this repository.

Cheers,

@mobbsie

### CODE REVIEW

**Comment by nozzlegear** [comment]
Glad to see this! It looks like it's written for version 3, which is understandable. Would you mind trying to convert it to v4? If not I could do it myself whenever I get the chance.

**Comment by mobbsie** [comment]
Hi @nozzlegear,
Yes sure, sorry about that.  I haven't actually updated my repository to version 4 but will do so and then make the amendments to this code.
I will commit the changes as soon as possible.

**Comment by nozzlegear** [comment]
Awesome! Let me know if you need any help or guidance with it.

**Comment by alectec** [comment]
Because @mobbsie took over the remainder of the Abandoned Cart functionality, I started on the Province and Country, which go together.  I should have that ready by this weekend.  I'll need to update to v4, as well.

**Comment by nozzlegear** [comment]
Great @alectec, looking forward to it!

**Comment by lasamuadib** [comment]
Hello, I was wondering if this functionality had been committed to the master branch yet?  This is something that would definitely help out with a request we are working on for our store.

**Comment by mobbsie** [comment]
Hi @lasamuadib,
I committed this to the version 3 branch but unfortunately I haven't had the time to convert it to v4.  I probably won't get around to it for at least 6 weeks, but I will do so as soon as I can.

**Comment by lasamuadib** [comment]
Thanks for the update!

**Comment by nozzlegear** [comment]
Just an update for those that are watching this, @lasamuadib has submitted a pull request for the Abandoned Carts API in #178. Thanks for the pull request @mobbsie, sorry version 4 came at a bad time and messed it all up! 🙍

**Comment by mobbsie** [comment]
No problem @nozzlegear. Thanks for the swift turnaround on the v4 edition @lasamuadib.

**Pull request closed without merging**
