### PR TITLE
Upgraded to API version 2022-04

### PR DESCRIPTION
**Pull request by clement911**

### CODE REVIEW

**Comment by clement911** [comment]
@nozzlegear  are you able to make a new release ?

**Comment by nozzlegear** [comment]
Sorry, I thought I replied to the Github email a few days ago. Merging now!

**Comment by clement911** [comment]
Thank you! I'm looking forward to the release.

**Comment by clement911** [comment]
Hi @nozzlegear , will you be making a release soonish ?

**Comment by nozzlegear** [comment]
Yes, very soon! I'm hoping to finish up #745 soon and have the next release be the first real test run of that. If I don't have it finished in the next couple of days I'll go ahead and cut a release manually.

**Comment by clement911** [comment]
Awesome, thanks for your work on this.
If you can also merge https://github.com/nozzlegear/ShopifySharp/pull/749 that would be great.

**Comment by nozzlegear** [comment]
Released in 5.16.0 on nuget! Thanks for your patience!

**Comment by nozzlegear** [comment]
Yes, sorry! I’m at a wedding tonight and tomorrow but I’ll be working on this library once I’m back. I’ll merge and publish asap!

--
Josh Harms

**Pull request merged**
