### PR TITLE
Added presentment_prices and sub properties in ProductVariant

### PR DESCRIPTION
**Pull request by ajayak**
https://help.shopify.com/en/api/reference/products/product-variant

### CODE REVIEW

**Comment by ajayak** [comment]
@nozzlegear added missing properties in Product Variant :)

**Comment by clement911** [comment]
Cool.
There are actually multi-currency properties that need to be added across the board for all money fields in other entities such as order and transactions.
That's a start!

**Comment by ajayak** [comment]
@clement911 Updated! Is it possible to get a minor release with these changes? :)

**Comment by clement911** [comment]
Looking pretty good I think!

**Comment by nozzlegear** [comment]
Published in 4.21.1, thank you! @clement911 thanks for reviewing, it helps a ton!

**Pull request merged**
