### PR TITLE
Typos + 1 new draft order property

### PR DESCRIPTION
**Pull request by clement911**
Mostly typos + 1 new draft order property.

### CODE REVIEW

**Comment by clement911** [comment]
Hi @nozzlegear .
Are you able to merge and release?
Without date properties being datetimeoffset , they are automatically converted to the machine's timezone, which is probably not what is expected.
I don't believe it is a breaking change because DateTimeOffset implicitely converts to DateTime so it should not produce any compilation errors to update.

I also convert Price.Amount from a string to a decimal, which is a broken change, but that would have definitely been a typo that was introduced earlier.

**Comment by nozzlegear** [comment]
Sure! I can merge it this morning.

--
Josh Harms

**Comment by clement911** [comment]
Awesome!

**Comment by clement911** [comment]
Thanks for the quick turn around!

**Pull request merged**
