### PR TITLE
Added Abandoned checkout functionality

### PR DESCRIPTION
**Pull request by lasamuadib**
Since [mobbsie](https://github.com/mobbsie) said it would be at least 6 weeks to get his changes for abandoned carts ported to version 4 I took a stab at it myself and got it working.

None of this code was taken from mobbsie's work and was created using entities existing in the 4.0 branch.

This is my first contribution on GitHub so hopefully I haven't stepped on anyone's toes.

### CODE REVIEW

**Comment by lasamuadib** [comment]
I'll take a look and see what I can get put together.

**Comment by lasamuadib** [comment]
I had included a couple basic tests when I did the first submission.  I
looked into expanding those to include what you've requested, but I don't
think it's going to work.  For instance in my review of the data the
BillingAddress is null.  The ShippingAddress is also null.  The Customer is
a valid structure so I will work on iterating through the returned
checkouts and validating the customer values exist.

Are there any others specifically that you would like tested for?

On Mon, Oct 9, 2017 at 1:20 PM, Jonathan Nordell <jonathan.nordell@gmail.com

**Comment by nozzlegear** [comment]
Oh shoot, sorry I somehow missed that you already had that test file there. For now if you could just add some tests on whatever simple properties you see coming back in your requests that should be fine. So test that the `CartToken` prop isn't null if that's what you see, and that the `Customer` isn't null, etc. Nothing too fancy, I'll expand the tests in the future if it's ever necessary. I just want to make sure it's returning and parsing property names correctly right now. 

Also, in your current tests it'd be great if you could change the assert count > 0 to `>= 0` as the automated tests for this package run on a dev shop that doesn't have any abandoned checkouts 😉

**Comment by lasamuadib** [comment]
I added more to the tests and added an entity for CheckoutLineItem for a couple additional fields over the standard LineItem entity.  I see them synced in with my fork, but I honestly don't know if they have been added to this pull request or not.

**Comment by nozzlegear** [comment]
They have! Pull requests on GitHub will be automatically updated whenever you push changes to the git branch (your master branch in this case) that opened the pull request.

**Comment by nozzlegear** [comment]
Looks like the tests are passing. I've merged your changes and will publish them to Nuget later this evening. Thanks for contributing! 👍

**Comment by nozzlegear** [comment]
Okay, sorry that took longer than expected; had some issues with failing tests for a different service. Your changes are now available on Nuget in version 4.5.0. Thanks again!

**Pull request merged**
